#!/bin/bash

year=`date +%G`
month=`date +%m`
day=`date +%d`

echo "Today is $year / $month / $day"

# Create YEAR directory if it does not already exist
if [ ! -d "$year" ]; then
    mkdir $year
fi

if [ -d "$year" ]; then
    echo "Adding new entry to directory $year."
fi

cd $year
filename=$year-$month-$day.ipynb

if [ -f "$filename" ]; then
    echo "A file called '$filename' already exists in diretory $year. Aborting addition of new entry."
    exit
fi

# Copy the template entry into the YEAR directory
cp ../.template/entry.ipynb $filename

# Make a few substitutions, setting the current date inside the copied template entry
sed -i "s/@year/$year/g" $filename
sed -i "s/@MONTH/`date +%B`/g" $filename
sed -i "s/@dday/$day/g" $filename
sed -i "s/@day/`date +%-e`/g" $filename

echo "Finished adding $filename to $year."

# You may want to comment out the next two lines which immediately launch the IPython notebook
echo "Launching IPython Notebook."
ipython notebook --pylab inline  &> /dev/null &

exit
